### ISSUE TITLE
Exiting from containers

### ISSUE THREAD

**Issue by manuparra** [AlvaroRodriguezGallardo/src-brokering#2]
Try to improve it @AlvaroRodriguezGallardo 

https://github.com/AlvaroRodriguezGallardo/src-brokering/blob/c12765c772efa2e4a49d510ba572b7cf59069d0e/example-fn/exercise_fn.py#L50C61-L50C61

Two options:
- Use logging package to print something as a log
- Use exit with an error code, in this case >0

Ideally, you have to implement the first one.
Implement the first option to output to the log system of the container. With it, when you use `docker logs <container>` you will get the operations, warnings, etc. 

So, use log for each action in your function.

To do it, create now a new branch and work with this new branch.

**Comment by AlvaroRodriguezGallardo** [comment]
I have done it. I have programmed many logs in actions I thaught are importants. Besides, the modified script is in a new branch

**Comment by manuparra** [comment]
It looks fine!
