### ISSUE TITLE
Remove this line and add a new one with the logging package

### ISSUE THREAD

**Issue by manuparra** [AlvaroRodriguezGallardo/src-brokering#3]
https://github.com/AlvaroRodriguezGallardo/src-brokering/blob/a3e7af82dfbba7263f3cff65653650fab12b6cfe/example-fn/exercise_fn.py#L60

**Comment by AlvaroRodriguezGallardo** [comment]
Done! However, in Dockerfile it is had '-/' folder as default, so it may not enter in that condition

**Comment by manuparra** [comment]
Okay! Done
