### ISSUE TITLE
Optimise image

### ISSUE THREAD

**Issue by manuparra** [AlvaroRodriguezGallardo/src-brokering#4]
Latest image was done by using python/ubuntu. The size of this image is around 1.5 GB. The idea now is to use an optimised version of the container with `alpine` for example and to reduce the size of the image.

https://github.com/AlvaroRodriguezGallardo/src-brokering/blob/5936cd36a1daa00126b1cbec34870a38be1c2246/example-fn/Dockerfile#L3

`Alpine` OS is not using the standard `glibc` so several packages will not work as usual.

Create a new branch, named: `example-fn-optimised` and create there all the files, etc.

**Comment by AlvaroRodriguezGallardo** [comment]
Done!

**Comment by manuparra** [comment]
Great. Now alpine will reduce the size of the image.
