### ISSUE TITLE
Improvements within Branches and DockerHub

### ISSUE THREAD

**Issue by manuparra** [AlvaroRodriguezGallardo/src-brokering#6]
Rename folders `example-fn` to <same of the brach>. i.e: `example-fn` (branch optimised) --> `example-fn-optimised`

This implies a change in the documentation:
- within each function folder, describe the procedure to build, run, etc. (like the main `README.md`) but explaining the changes and updates for this function, including the how to..,.etc.

Maintain one `README.md` at the first level, that link to the rest of the functions folder.

*Second*: 
- Create a dockerhub account (free), and upload your `opencv-python-alpine` image, then build the `Dockerfile` related calling with `FROM` to this `dockerhub` (locally or from `dockerhub`)

**Comment by AlvaroRodriguezGallardo** [comment]
I think the first is done

**Comment by AlvaroRodriguezGallardo** [comment]
About the second, locally it works correctly. However, 'docker login' makes an exception when I introduce my credentials, so I will try later

**Comment by AlvaroRodriguezGallardo** [comment]
Keeps failing when I try to enter with 'docker login'

**Comment by manuparra** [comment]
Done
